export const MIGRATIONS = [
  {
    id: "001_initial",
    sql: `
      CREATE TABLE categories (id SERIAL PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, description TEXT, image_url TEXT, sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'));
      CREATE TABLE products (id SERIAL PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, description TEXT NOT NULL DEFAULT '', price NUMERIC NOT NULL, compare_at_price NUMERIC, category_id INTEGER NOT NULL REFERENCES categories(id) ON DELETE CASCADE, image_url TEXT, image_alt_text TEXT, featured BOOLEAN NOT NULL DEFAULT false, created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'));
      CREATE TABLE product_variants (id SERIAL PRIMARY KEY, product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE, size TEXT NOT NULL, color TEXT NOT NULL, stock INTEGER NOT NULL DEFAULT 0, sku TEXT NOT NULL UNIQUE);
      CREATE TABLE admin_users (id SERIAL PRIMARY KEY, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'));
      CREATE TABLE sessions (id TEXT PRIMARY KEY, admin_user_id INTEGER NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE, expires_at TEXT NOT NULL);
      CREATE TABLE customer_users (id SERIAL PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, display_name TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'));
      CREATE TABLE customer_sessions (id TEXT PRIMARY KEY, customer_id INTEGER NOT NULL REFERENCES customer_users(id) ON DELETE CASCADE, expires_at TEXT NOT NULL);
      CREATE TABLE product_reviews (id SERIAL PRIMARY KEY, product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE, customer_id INTEGER REFERENCES customer_users(id) ON DELETE CASCADE, admin_user_id INTEGER REFERENCES admin_users(id) ON DELETE SET NULL, rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5), text TEXT, visible BOOLEAN NOT NULL DEFAULT true, created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), CHECK (customer_id IS NOT NULL OR admin_user_id IS NOT NULL));
      CREATE UNIQUE INDEX product_reviews_customer_product ON product_reviews (customer_id, product_id) WHERE customer_id IS NOT NULL;
      CREATE TABLE visitor_sessions (id TEXT PRIMARY KEY, created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), expires_at TEXT NOT NULL);
      CREATE TABLE cart_items (id SERIAL PRIMARY KEY, session_id TEXT NOT NULL REFERENCES visitor_sessions(id) ON DELETE CASCADE, variant_id INTEGER NOT NULL REFERENCES product_variants(id) ON DELETE CASCADE, quantity INTEGER NOT NULL DEFAULT 1, added_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), UNIQUE(session_id, variant_id));
      CREATE TABLE orders (id SERIAL PRIMARY KEY, order_number TEXT NOT NULL UNIQUE, customer_id INTEGER REFERENCES customer_users(id) ON DELETE SET NULL, visitor_session_id TEXT REFERENCES visitor_sessions(id) ON DELETE SET NULL, status TEXT NOT NULL DEFAULT 'pending', email TEXT NOT NULL, name TEXT NOT NULL, address TEXT NOT NULL, city TEXT NOT NULL, postal_code TEXT NOT NULL, country TEXT NOT NULL DEFAULT '', phone TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', subtotal NUMERIC NOT NULL, total NUMERIC NOT NULL, created_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), updated_at TEXT NOT NULL DEFAULT to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'));
      CREATE TABLE order_items (id SERIAL PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_name TEXT NOT NULL, product_slug TEXT NOT NULL, variant_size TEXT NOT NULL, variant_color TEXT NOT NULL, price NUMERIC NOT NULL, quantity INTEGER NOT NULL, total NUMERIC NOT NULL);
    `,
  },
];
